---

- name: Check for {{ staging_folder }}/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz  on local
  local_action: stat path={{ staging_folder }}/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz 
  become: no
  register: tomcat_archive_local_src

- name: Copy {{ staging_folder }}/tomcat/apache-tomcat-{{tomcat_version}}.tar.gz  if available
  copy:
    src: "{{ staging_folder }}/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
  when: tomcat_archive_local_src.stat.exists == True

- name: Download tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
           dest=/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
  when: tomcat_archive_local_src.stat.exists == False

- name: Extract tomcat archive
  unarchive:
    src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    dest: /opt
    remote_src: yes

- name: Download tomcat extras libralies
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_version}}/bin/extras/{{ item.name }}
           dest=/opt/apache-tomcat-{{ tomcat_version }}/{{ item.dir }}/
  with_items:
    - { name: catalina-jmx-remote.jar  , dir: lib }
    - { name: tomcat-juli-adapters.jar , dir: lib }
    - { name: tomcat-juli.jar          , dir: bin }

- name: Remove docs apps
  file: path=/opt/apache-tomcat-{{ tomcat_version }}/webapps/docs state=absent

- name: Remove examples apps
  file: path=/opt/apache-tomcat-{{ tomcat_version }}/webapps/examples state=absent

- name: Remove logging.properties
  file: path=/opt/apache-tomcat-{{ tomcat_version }}/conf/logging.properties state=absent

- name: Add tomcat environment file
  template: src=tomcat/bin/setenv.sh dest=/opt/apache-tomcat-{{ tomcat_version }}/bin/setenv.sh mode=0755

- name: Add tomcat configuration files - templates
  template: src=tomcat/conf/{{ item }} dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/{{ item }}
  with_items:
    - server.xml
    - tomcat-users.xml

- name: Remove home directory symlink
  file: path=/opt/tomcat state=absent

- name: Create home directory symlink (Temporary for useradd)
  file: src=/opt/apache-tomcat-{{ tomcat_version }} path=/opt/tomcat state=link

- name: Create tomcat group
  group: name=tomcat

- name: Create tomcat user
  user: name=tomcat group=tomcat home=/opt/tomcat

- name: Remove home directory symlink (again)
  file: path=/opt/tomcat state=absent

- name: Change tomcat directory permissions
  file: path=/opt/apache-tomcat-{{ tomcat_version }} owner=tomcat group=tomcat state=directory recurse=yes

- name: Recreate home directory symlink
  file: src=/opt/apache-tomcat-{{ tomcat_version }} owner=tomcat group=tomcat path=/opt/tomcat state=link

- name: Add tomcat systemd unit file
  copy: src=sysvinit/tomcat-initscript.sh dest=/etc/init.d/tomcat owner=root group=root mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: deploy iptables rules
  template: src=iptables/iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: Wait for tomcat started
  wait_for: port={{ http_port }}

